import Database from "better-sqlite3";
import fs from "fs";
import path from "path";

const DB_PATH = path.join(process.cwd(), "data", "db2.sqlite");
const OUT = path.join(process.cwd(), "docs", "business", "01-data-model.md");

const PURPOSES: Record<string, string> = {
  o_user: "Login accounts. Seeded with a default admin (see `src/lib/initDB.ts`).",
  o_project:
    "Project entity (a novel adaptation). Holds projectType, novel info, chosen image/video models, artStyle, directorManual, videoRatio, mode.",
  o_artStyle: "Art-style presets (name, label, prompt, preview image fileUrl in OSS).",
  o_agentDeploy:
    "Per-agent-key AI model deployment: `key` = agent key (`scriptAgent`, `productionAgent`, `universalAi`, `scriptAgent:decisionAgent`, ...), `modelName` = `<vendorId>:<modelName>`, plus temperature/maxOutputTokens/disabled/type.",
  o_setting: "App-wide key/value settings: `tokenKey` (JWT secret), `agentUseMode` (0 simple / 1 advanced), memory tuning, `switchAiDevTool`, etc.",
  o_tasks: "AI generation task records. `taskClass` groups tasks, `relatedObjects` lists affected ids, `state` = 进行中/成功/失败 (in-flight rows are filtered out of polling endpoints).",
  o_prompt: "Reusable prompt templates (`data`, `useData`).",
  o_modelPrompt: "Binding of an image/video model to a video-prompt template file under `data/modelPrompt/video/*.md`.",
  o_novel: "Novel chapters. `chapterData` = raw novel text, `event`/`eventState` = extraction result from `u.cleanNovel`.",
  o_event: "Extracted chapter events (AI-generated from novel text).",
  o_eventChapter: "Join: event ↔ novel chapter (`eventId`, `novelId`).",
  o_script: "Generated scripts. `content` = the `<scriptItem>` XML; `extractState` tracks asset extraction.",
  o_scriptAssets: "Join: script ↔ asset (`scriptId`, `assetId`).",
  o_assets:
    "Asset center entries (derived assets, storyboard assets, character/scene/role images). Links to `o_image` via `imageId`; `promptState` tracks prompt generation.",
  o_image: "Image records. `filePath` → OSS, `state` = 生成中/成功/失败, `model`/`resolution`, `errorReason`.",
  o_assets2Storyboard: "Join: storyboard panel ↔ asset (a panel may reuse existing assets).",
  o_assetsRole2Audio: "Join: role asset ↔ matched audio asset (cornerScape voice matching).",
  o_storyboard:
    "Storyboard panels: prompt, filePath (OSS image), state, track/trackId, `shouldGenerateImage`, videoDesc. Also the derive-asset lineage via `assetsId`-style links.",
  o_agentWorkData: "Agent workspace/plan data: `projectId` + `episodesId` + `key` (storySkeleton, adaptationStrategy, scriptPlan, storyboardTable, ...) → `data` JSON string.",
  o_video: "Generated video records (workbench): filePath, state, videoTrackId, errorReason.",
  o_videoTrack: "Video timeline tracks on the workbench: prompt, duration, selectVideoId, state.",
  o_imageFlow: "Image-flow editor graphs (JSON node graph in `flowData`).",
  o_vendorConfig:
    "Vendor (LLM provider) config: `id` = vendor id, `inputValues` = baseURL/apiKey/etc, `models` = available models JSON, `enable` flag. Vendor template code lives on disk in `data/vendor/<id>.ts`.",
  o_skillList: "Installed skills registry: name, description, path, md5, embedding (for retrieval), state.",
  o_skillAttribution: "Skill ↔ attribution binding (`skillId`, `attribution` = project/agent scope).",
  memories: "Agent conversation memory. Keyed by `isolationKey` (`projectId:agentType[:episodesId]`); `type` = message|summary; `embedding` = ONNX vector for RAG; `relatedMessageIds` for thread linking.",
};

function esc(ident: string): string {
  return JSON.stringify(ident);
}

function main() {
  const db = new Database(DB_PATH, { readonly: true });
  const tables = db
    .prepare("select name from sqlite_master where type='table' and name not like 'sqlite_%' order by name")
    .all()
    .map((r: { name: string }) => r.name);

  const out: string[] = [];
  out.push("# Toonflow Data Model (db2.sqlite)");
  out.push("");
  out.push(`- DB file: \`data/db2.sqlite\` (knex + better-sqlite3) — **gitignored runtime user data**`);
  out.push(`- Schema + seed data source: \`src/lib/initDB.ts\`; boot-time migrations/repairs: \`src/lib/fixDB.ts\``);
  out.push(`- Table TS types: \`src/types/database.d.ts\` (auto-generated by \`@rmp135/sql-ts\` in dev)`);
  out.push(`- Generated by \`yarn docs:data-model\`. Do not edit by hand.`);
  out.push("");
  out.push(`## Tables (${tables.length})`);
  out.push("");
  out.push("| Table | Purpose | Rows |");
  out.push("|---|---|---|");
  for (const t of tables) {
    const count = (db.prepare(`select count(*) as c from ${esc(t)}`).get() as { c: number }).c;
    out.push(`| \`${t}\` | ${PURPOSES[t] ?? ""} | ${count} |`);
  }

  for (const t of tables) {
    out.push("");
    out.push(`## \`${t}\``);
    out.push("");
    if (PURPOSES[t]) {
      out.push(PURPOSES[t]);
      out.push("");
    }
    const cols = db.prepare(`PRAGMA table_info(${esc(t)})`).all() as {
      cid: number;
      name: string;
      type: string;
      notnull: number;
      dflt_value: string | null;
      pk: number;
    }[];
    out.push("| Col | Type | PK |");
    out.push("|---|---|---|");
    for (const c of cols) {
      out.push(`| \`${c.name}\` | ${c.type || "-"} | ${c.pk ? "✅" : ""} |`);
    }
    const idxs = db.prepare(`PRAGMA index_list(${esc(t)})`).all() as { name: string; origin: string; unique: number }[];
    if (idxs.some((i) => i.origin === "c" || i.origin === "u")) {
      out.push("");
      out.push("Indexes:");
      for (const i of idxs) {
        if (i.origin !== "c" && i.origin !== "u") continue;
        const cols2 = db.prepare(`PRAGMA index_info(${esc(i.name)})`).all() as { name: string }[];
        out.push(`- \`${i.name}\`${i.unique ? " (unique)" : ""} on ${cols2.map((c) => `\`${c.name}\``).join(", ")}`);
      }
    }
  }

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, out.join("\n"), "utf8");
  db.close();
  console.log(`Wrote ${OUT} (${tables.length} tables)`);
}

try {
  main();
} catch (err) {
  console.error("Failed to read db2.sqlite. Does it exist? Run the app once or check data/.");
  console.error((err as Error).message);
  process.exit(1);
}
