import fs from "fs";
import path from "path";

const INDEX = path.join(process.cwd(), ".opencode", "index", "code-index.json");
const OUT = path.join(process.cwd(), "docs", "business", "02-routes-map.md");

const MODULES: Record<string, string> = {
  agents: "Agent conversation memory management (clear/get memory).",
  artStyle: "Art-style presets CRUD + AI style-prompt extraction.",
  assets: "Assets center: CRUD `o_assets`/`o_image`, audio assets, clip upload, material lists, polling.",
  assetsGenerate: "Trigger AI generation of asset images (fire-and-forget + task row), prompt polishing, cancel.",
  common: "Generic helpers (get big image from thumbnail).",
  cornerScape: "Role→audio voice matching (AI picks audio per character).",
  general: "Dashboard: project statistics, single project get/update.",
  login: "JWT login (`o_user` + `o_setting.tokenKey`). Only unauthenticated endpoint.",
  modelSelect: "List/detail AI models from enabled vendors.",
  novel: "Novel (chapters) CRUD; `novel/event/*` = chapter event extraction + event CRUD.",
  other: "Maintenance: delete all data, app version.",
  production: "Production pipeline: flow data, storyboard CRUD, image-flow editor, workbench video tracks.",
  project: "Project CRUD, director manual, visual manual (skill `.md` on disk).",
  script: "Script CRUD, export, AI asset extraction, polling.",
  scriptAgent: "Script-agent plan read/write (`o_agentWorkData`) + script upsert.",
  setting: "App settings (see grouped list below).",
  task: "Task center: paginated `o_tasks` queries, categories, details.",
  test: "Dev stub.",
};

const SETTING_GROUPS: Record<string, string> = {
  about: "App update check / installer download.",
  agentDeploy: "Per-agent model deployment (`o_agentDeploy`), simple/advanced mode.",
  dbConfig: "DB info (`sqlite_master`), clear tables/data, export/import JSON.",
  dev: "Toggle AI dev-tool.",
  fileManagement: "Open a folder in the OS.",
  loginConfig: "User/password management.",
  memoryConfig: "Agent memory tuning (upserts `o_setting` keys).",
  modelMap: "Bind image/video models to video-prompt template files; prompt CRUD.",
  promptManage: "Prompt template CRUD (`o_prompt`).",
  skillManagement: "Skill `.md` files on disk + `o_skillList`.",
  vendorConfig: "Vendor CRUD (code compiled in vm2 sandbox), enable/disable, model tests.",
};

function main() {
  if (!fs.existsSync(INDEX)) {
    console.error("Missing code index. Run `yarn index:generate` first.");
    process.exit(1);
  }
  const index = JSON.parse(fs.readFileSync(INDEX, "utf8"));
  const routes: Record<string, string> = index.routes;

  const byModule = new Map<string, string[]>();
  for (const [file, apiPath] of Object.entries(routes) as [string, string][]) {
    const seg = apiPath.split("/")[2] ?? "";
    const arr = byModule.get(seg) ?? [];
    arr.push(`\`${apiPath}\` ← ${file}`);
    byModule.set(seg, arr);
  }

  const out: string[] = [];
  out.push("# Toonflow REST API Map");
  out.push("");
  out.push(`- ${Object.keys(routes).length} endpoints, auto-registered from \`src/routes/**/*.ts\` (see \`src/core.ts\`).`);
  out.push("- All endpoints require JWT (`Authorization: Bearer <token>`, from `o_setting.tokenKey`) except `/api/login/login`.");
  out.push("- Response envelope: `{code: 200|400, data, message}` via `src/lib/responseFormat.ts`.");
  out.push("- Validation: zod `validateFields` middleware (400 on failure, Chinese messages).");
  out.push("- Generated by `yarn docs:routes`. Do not edit by hand.");
  out.push("");

  const sortedModules = [...byModule.keys()].sort();
  for (const mod of sortedModules) {
    const items = byModule.get(mod)!.sort();
    out.push(`## \`/api/${mod}\``);
    out.push("");
    out.push(MODULES[mod] ?? "");
    out.push("");
    for (const it of items) out.push(`- ${it}`);
    out.push("");
  }

  out.push("## `/api/setting` groups");
  out.push("");
  for (const [g, desc] of Object.entries(SETTING_GROUPS)) {
    const items = (byModule.get("setting") ?? []).filter((l) => l.includes(`/api/setting/${g}/`));
    if (items.length === 0) continue;
    out.push(`### ${g} — ${desc}`);
    out.push("");
    for (const it of items.sort()) out.push(`- ${it}`);
    out.push("");
  }

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, out.join("\n"), "utf8");
  console.log(`Wrote ${OUT}`);
}

main();
